pipeline{
    agent any
    stages{
        stage('Build'){
            steps{
                scripts{
                    checkout([$class: 'GitSCM', branches: [[name: 'pipelinetesting']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/getyourdurga/simple-java-maven-app.git']]])

                }
            }

        }
         
    }
}